[build]
  # Diretório do frontend
  base = "frontend/"
  
  # Comando de build
  command = "npm install && npm run build:netlify"
  
  # Diretório de publicação (arquivos estáticos)
  publish = "."

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

# Redirecionamentos para SPA
[[redirects]]
  from = "/api/*"
  to = "https://controle-combustivel.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:;"

# Cache para arquivos estáticos
[[headers]]
  for = "/src/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
