services:
  - type: web
    name: controle-combustivel-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && cd backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: 1
      # Adicione suas outras variáveis de ambiente aqui
      # DATABASE_URL, JWT_SECRET, etc. devem ser configurados no dashboard do Render
